---
# tasks file for jenkins
- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present
- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started
